name: Update KKPRL JSON

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Download KKPRL JSON from ArcGIS
      run: |
        curl -k "https://arcgis.ruanglaut.id/arcgis/rest/services/KKPRL/KKPRL/FeatureServer/1/query?where=1=1&outFields=*&returnGeometry=true&f=json" -o kkprl.json

    - name: Commit and push if changed
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@users.noreply.github.com"
        git add kkprl.json
        git diff --cached --quiet || git commit -m "Auto-update kkprl.json"
        git push
